/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int PI_FUN(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int PI_FUN_alloc_mem(void);
extern "C" int PI_FUN_init_mem(int mem);
extern "C" void PI_FUN_free_mem(int mem);
extern "C" int PI_FUN_checkout(void);
extern "C" void PI_FUN_release(int mem);
extern "C" void PI_FUN_incref(void);
extern "C" void PI_FUN_decref(void);
extern "C" casadi_int PI_FUN_n_out(void);
extern "C" casadi_int PI_FUN_n_in(void);
extern "C" casadi_real PI_FUN_default_in(casadi_int i);
extern "C" const char* PI_FUN_name_in(casadi_int i);
extern "C" const char* PI_FUN_name_out(casadi_int i);
extern "C" const casadi_int* PI_FUN_sparsity_in(casadi_int i);
extern "C" const casadi_int* PI_FUN_sparsity_out(casadi_int i);
extern "C" int PI_FUN_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int PI_CSI_FUN(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int PI_CSI_FUN_alloc_mem(void);
extern "C" int PI_CSI_FUN_init_mem(int mem);
extern "C" void PI_CSI_FUN_free_mem(int mem);
extern "C" int PI_CSI_FUN_checkout(void);
extern "C" void PI_CSI_FUN_release(int mem);
extern "C" void PI_CSI_FUN_incref(void);
extern "C" void PI_CSI_FUN_decref(void);
extern "C" casadi_int PI_CSI_FUN_n_out(void);
extern "C" casadi_int PI_CSI_FUN_n_in(void);
extern "C" casadi_real PI_CSI_FUN_default_in(casadi_int i);
extern "C" const char* PI_CSI_FUN_name_in(casadi_int i);
extern "C" const char* PI_CSI_FUN_name_out(casadi_int i);
extern "C" const casadi_int* PI_CSI_FUN_sparsity_in(casadi_int i);
extern "C" const casadi_int* PI_CSI_FUN_sparsity_out(casadi_int i);
extern "C" int PI_CSI_FUN_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int CSI_FUN(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int CSI_FUN_alloc_mem(void);
extern "C" int CSI_FUN_init_mem(int mem);
extern "C" void CSI_FUN_free_mem(int mem);
extern "C" int CSI_FUN_checkout(void);
extern "C" void CSI_FUN_release(int mem);
extern "C" void CSI_FUN_incref(void);
extern "C" void CSI_FUN_decref(void);
extern "C" casadi_int CSI_FUN_n_out(void);
extern "C" casadi_int CSI_FUN_n_in(void);
extern "C" casadi_real CSI_FUN_default_in(casadi_int i);
extern "C" const char* CSI_FUN_name_in(casadi_int i);
extern "C" const char* CSI_FUN_name_out(casadi_int i);
extern "C" const casadi_int* CSI_FUN_sparsity_in(casadi_int i);
extern "C" const casadi_int* CSI_FUN_sparsity_out(casadi_int i);
extern "C" int CSI_FUN_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
