/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int CTRL(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int CTRL_alloc_mem(void);
extern "C" int CTRL_init_mem(int mem);
extern "C" void CTRL_free_mem(int mem);
extern "C" int CTRL_checkout(void);
extern "C" void CTRL_release(int mem);
extern "C" void CTRL_incref(void);
extern "C" void CTRL_decref(void);
extern "C" casadi_int CTRL_n_out(void);
extern "C" casadi_int CTRL_n_in(void);
extern "C" casadi_real CTRL_default_in(casadi_int i);
extern "C" const char* CTRL_name_in(casadi_int i);
extern "C" const char* CTRL_name_out(casadi_int i);
extern "C" const casadi_int* CTRL_sparsity_in(casadi_int i);
extern "C" const casadi_int* CTRL_sparsity_out(casadi_int i);
extern "C" int CTRL_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
