/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int X_DOT(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int X_DOT_alloc_mem(void);
extern "C" int X_DOT_init_mem(int mem);
extern "C" void X_DOT_free_mem(int mem);
extern "C" int X_DOT_checkout(void);
extern "C" void X_DOT_release(int mem);
extern "C" void X_DOT_incref(void);
extern "C" void X_DOT_decref(void);
extern "C" casadi_int X_DOT_n_out(void);
extern "C" casadi_int X_DOT_n_in(void);
extern "C" casadi_real X_DOT_default_in(casadi_int i);
extern "C" const char* X_DOT_name_in(casadi_int i);
extern "C" const char* X_DOT_name_out(casadi_int i);
extern "C" const casadi_int* X_DOT_sparsity_in(casadi_int i);
extern "C" const casadi_int* X_DOT_sparsity_out(casadi_int i);
extern "C" int X_DOT_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
