/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jerk_allocation_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) (static_cast<double>(x))

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[59] = {6, 8, 0, 6, 12, 18, 24, 30, 36, 42, 48, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* A_jerk_fun:(i0[3],i1[4],i2[4])->(o0[6x8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a4, a5, a6, a7, a8, a9;
  a0=3.3333333333333331e-01;
  a1=arg[0]? arg[0][1] : 0;
  a2=cos(a1);
  a3=arg[0]? arg[0][2] : 0;
  a4=sin(a3);
  a5=(a2*a4);
  a5=(a0*a5);
  a6=1.4980000000000001e-05;
  a7=7.0710678118654757e-01;
  a8=arg[2]? arg[2][0] : 0;
  a9=sin(a8);
  a10=(a7*a9);
  a11=(a6*a10);
  a12=(a5*a11);
  a13=cos(a3);
  a2=(a2*a13);
  a2=(a0*a2);
  a14=-7.0710678118654746e-01;
  a9=(a14*a9);
  a15=(a6*a9);
  a16=(a2*a15);
  a12=(a12-a16);
  a16=sin(a1);
  a16=(a0*a16);
  a17=cos(a8);
  a18=(a6*a17);
  a19=(a16*a18);
  a12=(a12+a19);
  if (res[0]!=0) res[0][0]=a12;
  a12=arg[0]? arg[0][0] : 0;
  a19=sin(a12);
  a20=sin(a1);
  a21=(a19*a20);
  a22=(a21*a13);
  a23=cos(a12);
  a24=sin(a3);
  a25=(a23*a24);
  a22=(a22+a25);
  a22=(a0*a22);
  a25=(a22*a15);
  a3=cos(a3);
  a23=(a23*a3);
  a21=(a21*a4);
  a23=(a23-a21);
  a23=(a0*a23);
  a21=(a23*a11);
  a25=(a25+a21);
  a1=cos(a1);
  a19=(a19*a1);
  a19=(a0*a19);
  a21=(a19*a18);
  a25=(a25+a21);
  a25=(-a25);
  if (res[0]!=0) res[0][1]=a25;
  a25=cos(a12);
  a1=(a25*a1);
  a1=(a0*a1);
  a18=(a1*a18);
  a12=sin(a12);
  a24=(a12*a24);
  a25=(a25*a20);
  a13=(a25*a13);
  a24=(a24-a13);
  a24=(a0*a24);
  a15=(a24*a15);
  a25=(a25*a4);
  a12=(a12*a3);
  a25=(a25+a12);
  a0=(a0*a25);
  a11=(a0*a11);
  a15=(a15+a11);
  a18=(a18-a15);
  if (res[0]!=0) res[0][2]=a18;
  a18=4.7619047619047613e+01;
  a15=4.2369838328697928e-06;
  a11=(a15*a17);
  a25=-9.3600000000000002e-06;
  a12=(a25*a9);
  a11=(a11-a12);
  a11=(a18*a11);
  if (res[0]!=0) res[0][3]=a11;
  a11=-4.2369838328697936e-06;
  a12=(a11*a17);
  a3=(a25*a10);
  a12=(a12-a3);
  a12=(a18*a12);
  if (res[0]!=0) res[0][4]=a12;
  a12=2.7597321194265245e+01;
  a17=(a25*a17);
  a3=-4.2369838328697928e-06;
  a9=(a3*a9);
  a4=4.2369838328697936e-06;
  a10=(a4*a10);
  a9=(a9+a10);
  a17=(a17-a9);
  a17=(a12*a17);
  if (res[0]!=0) res[0][5]=a17;
  a17=arg[2]? arg[2][1] : 0;
  a9=sin(a17);
  a10=(a14*a9);
  a13=(a6*a10);
  a20=(a5*a13);
  a21=-7.0710678118654757e-01;
  a9=(a21*a9);
  a26=(a6*a9);
  a27=(a2*a26);
  a20=(a20-a27);
  a27=cos(a17);
  a28=(a6*a27);
  a29=(a16*a28);
  a20=(a20+a29);
  if (res[0]!=0) res[0][6]=a20;
  a20=(a22*a26);
  a29=(a23*a13);
  a20=(a20+a29);
  a29=(a19*a28);
  a20=(a20+a29);
  a20=(-a20);
  if (res[0]!=0) res[0][7]=a20;
  a28=(a1*a28);
  a26=(a24*a26);
  a13=(a0*a13);
  a26=(a26+a13);
  a28=(a28-a26);
  if (res[0]!=0) res[0][8]=a28;
  a28=(a4*a27);
  a26=9.3600000000000002e-06;
  a13=(a26*a9);
  a28=(a28-a13);
  a28=(a18*a28);
  if (res[0]!=0) res[0][9]=a28;
  a28=(a15*a27);
  a13=(a26*a10);
  a28=(a28-a13);
  a28=(a18*a28);
  if (res[0]!=0) res[0][10]=a28;
  a27=(a26*a27);
  a9=(a11*a9);
  a10=(a3*a10);
  a9=(a9+a10);
  a27=(a27-a9);
  a27=(a12*a27);
  if (res[0]!=0) res[0][11]=a27;
  a27=-7.0710678118654768e-01;
  a9=arg[2]? arg[2][2] : 0;
  a10=sin(a9);
  a28=(a27*a10);
  a13=(a6*a28);
  a20=(a5*a13);
  a29=7.0710678118654746e-01;
  a10=(a29*a10);
  a30=(a6*a10);
  a31=(a2*a30);
  a20=(a20-a31);
  a31=cos(a9);
  a32=(a6*a31);
  a33=(a16*a32);
  a20=(a20+a33);
  if (res[0]!=0) res[0][12]=a20;
  a20=(a22*a30);
  a33=(a23*a13);
  a20=(a20+a33);
  a33=(a19*a32);
  a20=(a20+a33);
  a20=(-a20);
  if (res[0]!=0) res[0][13]=a20;
  a32=(a1*a32);
  a30=(a24*a30);
  a13=(a0*a13);
  a30=(a30+a13);
  a32=(a32-a30);
  if (res[0]!=0) res[0][14]=a32;
  a32=(a3*a31);
  a30=(a25*a10);
  a32=(a32-a30);
  a32=(a18*a32);
  if (res[0]!=0) res[0][15]=a32;
  a32=(a4*a31);
  a30=(a25*a28);
  a32=(a32-a30);
  a32=(a18*a32);
  if (res[0]!=0) res[0][16]=a32;
  a31=(a25*a31);
  a10=(a15*a10);
  a28=(a11*a28);
  a10=(a10+a28);
  a31=(a31-a10);
  a31=(a12*a31);
  if (res[0]!=0) res[0][17]=a31;
  a31=7.0710678118654735e-01;
  a10=arg[2]? arg[2][3] : 0;
  a28=sin(a10);
  a32=(a31*a28);
  a30=(a6*a32);
  a13=(a5*a30);
  a20=7.0710678118654768e-01;
  a28=(a20*a28);
  a33=(a6*a28);
  a34=(a2*a33);
  a13=(a13-a34);
  a34=cos(a10);
  a35=(a6*a34);
  a36=(a16*a35);
  a13=(a13+a36);
  if (res[0]!=0) res[0][18]=a13;
  a13=(a22*a33);
  a36=(a23*a30);
  a13=(a13+a36);
  a36=(a19*a35);
  a13=(a13+a36);
  a13=(-a13);
  if (res[0]!=0) res[0][19]=a13;
  a35=(a1*a35);
  a33=(a24*a33);
  a30=(a0*a30);
  a33=(a33+a30);
  a35=(a35-a33);
  if (res[0]!=0) res[0][20]=a35;
  a35=(a11*a34);
  a33=(a26*a28);
  a35=(a35-a33);
  a35=(a18*a35);
  if (res[0]!=0) res[0][21]=a35;
  a35=-4.2369838328697919e-06;
  a33=(a35*a34);
  a30=(a26*a32);
  a33=(a33-a30);
  a33=(a18*a33);
  if (res[0]!=0) res[0][22]=a33;
  a34=(a26*a34);
  a28=(a4*a28);
  a33=4.2369838328697919e-06;
  a32=(a33*a32);
  a28=(a28+a32);
  a34=(a34-a28);
  a34=(a12*a34);
  if (res[0]!=0) res[0][23]=a34;
  a34=cos(a8);
  a7=(a7*a34);
  a28=(a6*a7);
  a32=arg[1]? arg[1][0] : 0;
  a28=(a28*a32);
  a30=(a5*a28);
  a34=(a14*a34);
  a13=(a6*a34);
  a13=(a13*a32);
  a36=(a2*a13);
  a30=(a30-a36);
  a8=sin(a8);
  a36=(a6*a8);
  a36=(a36*a32);
  a37=(a16*a36);
  a30=(a30-a37);
  if (res[0]!=0) res[0][24]=a30;
  a30=(a19*a36);
  a37=(a22*a13);
  a38=(a23*a28);
  a37=(a37+a38);
  a30=(a30-a37);
  if (res[0]!=0) res[0][25]=a30;
  a13=(a24*a13);
  a28=(a0*a28);
  a13=(a13+a28);
  a36=(a1*a36);
  a13=(a13+a36);
  a13=(-a13);
  if (res[0]!=0) res[0][26]=a13;
  a13=(a15*a8);
  a36=(a25*a34);
  a13=(a13+a36);
  a13=(a13*a32);
  a13=(a18*a13);
  a13=(-a13);
  if (res[0]!=0) res[0][27]=a13;
  a13=(a11*a8);
  a36=(a25*a7);
  a13=(a13+a36);
  a13=(a13*a32);
  a13=(a18*a13);
  a13=(-a13);
  if (res[0]!=0) res[0][28]=a13;
  a8=(a25*a8);
  a34=(a3*a34);
  a7=(a4*a7);
  a34=(a34+a7);
  a8=(a8+a34);
  a8=(a8*a32);
  a8=(a12*a8);
  a8=(-a8);
  if (res[0]!=0) res[0][29]=a8;
  a8=cos(a17);
  a14=(a14*a8);
  a32=(a6*a14);
  a34=arg[1]? arg[1][1] : 0;
  a32=(a32*a34);
  a7=(a5*a32);
  a21=(a21*a8);
  a8=(a6*a21);
  a8=(a8*a34);
  a13=(a2*a8);
  a7=(a7-a13);
  a17=sin(a17);
  a13=(a6*a17);
  a13=(a13*a34);
  a36=(a16*a13);
  a7=(a7-a36);
  if (res[0]!=0) res[0][30]=a7;
  a7=(a19*a13);
  a36=(a22*a8);
  a28=(a23*a32);
  a36=(a36+a28);
  a7=(a7-a36);
  if (res[0]!=0) res[0][31]=a7;
  a8=(a24*a8);
  a32=(a0*a32);
  a8=(a8+a32);
  a13=(a1*a13);
  a8=(a8+a13);
  a8=(-a8);
  if (res[0]!=0) res[0][32]=a8;
  a8=(a4*a17);
  a13=(a26*a21);
  a8=(a8+a13);
  a8=(a8*a34);
  a8=(a18*a8);
  a8=(-a8);
  if (res[0]!=0) res[0][33]=a8;
  a8=(a15*a17);
  a13=(a26*a14);
  a8=(a8+a13);
  a8=(a8*a34);
  a8=(a18*a8);
  a8=(-a8);
  if (res[0]!=0) res[0][34]=a8;
  a17=(a26*a17);
  a21=(a11*a21);
  a14=(a3*a14);
  a21=(a21+a14);
  a17=(a17+a21);
  a17=(a17*a34);
  a17=(a12*a17);
  a17=(-a17);
  if (res[0]!=0) res[0][35]=a17;
  a17=cos(a9);
  a27=(a27*a17);
  a34=(a6*a27);
  a21=arg[1]? arg[1][2] : 0;
  a34=(a34*a21);
  a14=(a5*a34);
  a29=(a29*a17);
  a17=(a6*a29);
  a17=(a17*a21);
  a8=(a2*a17);
  a14=(a14-a8);
  a9=sin(a9);
  a8=(a6*a9);
  a8=(a8*a21);
  a13=(a16*a8);
  a14=(a14-a13);
  if (res[0]!=0) res[0][36]=a14;
  a14=(a19*a8);
  a13=(a22*a17);
  a32=(a23*a34);
  a13=(a13+a32);
  a14=(a14-a13);
  if (res[0]!=0) res[0][37]=a14;
  a17=(a24*a17);
  a34=(a0*a34);
  a17=(a17+a34);
  a8=(a1*a8);
  a17=(a17+a8);
  a17=(-a17);
  if (res[0]!=0) res[0][38]=a17;
  a3=(a3*a9);
  a17=(a25*a29);
  a3=(a3+a17);
  a3=(a3*a21);
  a3=(a18*a3);
  a3=(-a3);
  if (res[0]!=0) res[0][39]=a3;
  a3=(a4*a9);
  a17=(a25*a27);
  a3=(a3+a17);
  a3=(a3*a21);
  a3=(a18*a3);
  a3=(-a3);
  if (res[0]!=0) res[0][40]=a3;
  a25=(a25*a9);
  a15=(a15*a29);
  a27=(a11*a27);
  a15=(a15+a27);
  a25=(a25+a15);
  a25=(a25*a21);
  a25=(a12*a25);
  a25=(-a25);
  if (res[0]!=0) res[0][41]=a25;
  a25=cos(a10);
  a31=(a31*a25);
  a21=(a6*a31);
  a15=arg[1]? arg[1][3] : 0;
  a21=(a21*a15);
  a5=(a5*a21);
  a20=(a20*a25);
  a25=(a6*a20);
  a25=(a25*a15);
  a2=(a2*a25);
  a5=(a5-a2);
  a10=sin(a10);
  a6=(a6*a10);
  a6=(a6*a15);
  a16=(a16*a6);
  a5=(a5-a16);
  if (res[0]!=0) res[0][42]=a5;
  a19=(a19*a6);
  a22=(a22*a25);
  a23=(a23*a21);
  a22=(a22+a23);
  a19=(a19-a22);
  if (res[0]!=0) res[0][43]=a19;
  a24=(a24*a25);
  a0=(a0*a21);
  a24=(a24+a0);
  a1=(a1*a6);
  a24=(a24+a1);
  a24=(-a24);
  if (res[0]!=0) res[0][44]=a24;
  a11=(a11*a10);
  a24=(a26*a20);
  a11=(a11+a24);
  a11=(a11*a15);
  a11=(a18*a11);
  a11=(-a11);
  if (res[0]!=0) res[0][45]=a11;
  a35=(a35*a10);
  a11=(a26*a31);
  a35=(a35+a11);
  a35=(a35*a15);
  a18=(a18*a35);
  a18=(-a18);
  if (res[0]!=0) res[0][46]=a18;
  a26=(a26*a10);
  a4=(a4*a20);
  a33=(a33*a31);
  a4=(a4+a33);
  a26=(a26+a4);
  a26=(a26*a15);
  a12=(a12*a26);
  a12=(-a12);
  if (res[0]!=0) res[0][47]=a12;
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int A_jerk_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT int A_jerk_fun_alloc_mem(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int A_jerk_fun_init_mem(int mem) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void A_jerk_fun_free_mem(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT int A_jerk_fun_checkout(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void A_jerk_fun_release(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT void A_jerk_fun_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void A_jerk_fun_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int A_jerk_fun_n_in(void) { return 3;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int A_jerk_fun_n_out(void) { return 1;}

extern "C" CASADI_SYMBOL_EXPORT casadi_real A_jerk_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* A_jerk_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* A_jerk_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* A_jerk_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* A_jerk_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT int A_jerk_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_A_jerk_fun(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[98];
  casadi_int *iw = 0;
  const casadi_real* arg[3] = {0};
  casadi_real* res[1] = {0};
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"A_jerk_fun\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"A_jerk_fun\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+59);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+3, casadi_s1, w+59);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+7, casadi_s1, w+59);
  --resc;
  res[0] = w+11;
  i = A_jerk_fun(arg, res, iw, w+59, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"A_jerk_fun\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s2, res[0]);
}
#endif

casadi_int main_A_jerk_fun(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[98];
  const casadi_real* arg[3];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+3;
  arg[2] = w+7;
  res[0] = w+11;
  a = w;
  for (j=0; j<11; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = A_jerk_fun(arg, res, iw, w+59, 0);
  if (flag) return flag;
  r = w+11;
  for (j=0; j<48; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}

/* jerk_ellips:(i0[3],i1[4],i2[4])->(o0[3x3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a6, a7, a8, a9;
  a0=3.3333333333333331e-01;
  a1=arg[0]? arg[0][0] : 0;
  a2=sin(a1);
  a3=arg[0]? arg[0][1] : 0;
  a4=sin(a3);
  a5=(a2*a4);
  a6=arg[0]? arg[0][2] : 0;
  a7=cos(a6);
  a8=(a5*a7);
  a9=cos(a1);
  a10=sin(a6);
  a11=(a9*a10);
  a8=(a8+a11);
  a8=(a0*a8);
  a11=1.4980000000000001e-05;
  a12=-7.0710678118654746e-01;
  a13=arg[2]? arg[2][0] : 0;
  a14=sin(a13);
  a15=(a12*a14);
  a15=(a11*a15);
  a16=(a8*a15);
  a17=cos(a6);
  a9=(a9*a17);
  a6=sin(a6);
  a5=(a5*a6);
  a9=(a9-a5);
  a9=(a0*a9);
  a5=7.0710678118654757e-01;
  a14=(a5*a14);
  a14=(a11*a14);
  a18=(a9*a14);
  a16=(a16+a18);
  a18=cos(a3);
  a2=(a2*a18);
  a2=(a0*a2);
  a19=cos(a13);
  a19=(a11*a19);
  a20=(a2*a19);
  a16=(a16+a20);
  a20=casadi_sq(a16);
  a21=-7.0710678118654757e-01;
  a22=arg[2]? arg[2][1] : 0;
  a23=sin(a22);
  a24=(a21*a23);
  a24=(a11*a24);
  a25=(a8*a24);
  a23=(a12*a23);
  a23=(a11*a23);
  a26=(a9*a23);
  a25=(a25+a26);
  a26=cos(a22);
  a26=(a11*a26);
  a27=(a2*a26);
  a25=(a25+a27);
  a27=casadi_sq(a25);
  a20=(a20+a27);
  a27=7.0710678118654746e-01;
  a28=arg[2]? arg[2][2] : 0;
  a29=sin(a28);
  a30=(a27*a29);
  a30=(a11*a30);
  a31=(a8*a30);
  a32=-7.0710678118654768e-01;
  a29=(a32*a29);
  a29=(a11*a29);
  a33=(a9*a29);
  a31=(a31+a33);
  a33=cos(a28);
  a33=(a11*a33);
  a34=(a2*a33);
  a31=(a31+a34);
  a34=casadi_sq(a31);
  a20=(a20+a34);
  a34=7.0710678118654768e-01;
  a35=arg[2]? arg[2][3] : 0;
  a36=sin(a35);
  a37=(a34*a36);
  a37=(a11*a37);
  a38=(a8*a37);
  a39=7.0710678118654735e-01;
  a36=(a39*a36);
  a36=(a11*a36);
  a40=(a9*a36);
  a38=(a38+a40);
  a40=cos(a35);
  a40=(a11*a40);
  a41=(a2*a40);
  a38=(a38+a41);
  a41=casadi_sq(a38);
  a20=(a20+a41);
  a41=sin(a13);
  a41=(a11*a41);
  a42=arg[1]? arg[1][0] : 0;
  a41=(a41*a42);
  a43=(a2*a41);
  a13=cos(a13);
  a44=(a12*a13);
  a44=(a11*a44);
  a44=(a44*a42);
  a45=(a8*a44);
  a5=(a5*a13);
  a5=(a11*a5);
  a5=(a5*a42);
  a42=(a9*a5);
  a45=(a45+a42);
  a43=(a43-a45);
  a45=casadi_sq(a43);
  a20=(a20+a45);
  a45=sin(a22);
  a45=(a11*a45);
  a42=arg[1]? arg[1][1] : 0;
  a45=(a45*a42);
  a13=(a2*a45);
  a22=cos(a22);
  a21=(a21*a22);
  a21=(a11*a21);
  a21=(a21*a42);
  a46=(a8*a21);
  a12=(a12*a22);
  a12=(a11*a12);
  a12=(a12*a42);
  a42=(a9*a12);
  a46=(a46+a42);
  a13=(a13-a46);
  a46=casadi_sq(a13);
  a20=(a20+a46);
  a46=sin(a28);
  a46=(a11*a46);
  a42=arg[1]? arg[1][2] : 0;
  a46=(a46*a42);
  a22=(a2*a46);
  a28=cos(a28);
  a27=(a27*a28);
  a27=(a11*a27);
  a27=(a27*a42);
  a47=(a8*a27);
  a32=(a32*a28);
  a32=(a11*a32);
  a32=(a32*a42);
  a42=(a9*a32);
  a47=(a47+a42);
  a22=(a22-a47);
  a47=casadi_sq(a22);
  a20=(a20+a47);
  a47=sin(a35);
  a47=(a11*a47);
  a42=arg[1]? arg[1][3] : 0;
  a47=(a47*a42);
  a2=(a2*a47);
  a35=cos(a35);
  a34=(a34*a35);
  a34=(a11*a34);
  a34=(a34*a42);
  a8=(a8*a34);
  a39=(a39*a35);
  a11=(a11*a39);
  a11=(a11*a42);
  a9=(a9*a11);
  a8=(a8+a9);
  a2=(a2-a8);
  a8=casadi_sq(a2);
  a20=(a20+a8);
  a8=cos(a1);
  a18=(a8*a18);
  a18=(a0*a18);
  a9=(a18*a19);
  a1=sin(a1);
  a10=(a1*a10);
  a8=(a8*a4);
  a4=(a8*a7);
  a10=(a10-a4);
  a10=(a0*a10);
  a4=(a10*a15);
  a8=(a8*a6);
  a1=(a1*a17);
  a8=(a8+a1);
  a8=(a0*a8);
  a1=(a8*a14);
  a4=(a4+a1);
  a9=(a9-a4);
  a4=casadi_sq(a9);
  a1=(a18*a26);
  a17=(a10*a24);
  a42=(a8*a23);
  a17=(a17+a42);
  a1=(a1-a17);
  a17=casadi_sq(a1);
  a4=(a4+a17);
  a17=(a18*a33);
  a42=(a10*a30);
  a39=(a8*a29);
  a42=(a42+a39);
  a17=(a17-a42);
  a42=casadi_sq(a17);
  a4=(a4+a42);
  a42=(a18*a40);
  a39=(a10*a37);
  a35=(a8*a36);
  a39=(a39+a35);
  a42=(a42-a39);
  a39=casadi_sq(a42);
  a4=(a4+a39);
  a39=(a10*a44);
  a35=(a8*a5);
  a39=(a39+a35);
  a35=(a18*a41);
  a39=(a39+a35);
  a35=casadi_sq(a39);
  a4=(a4+a35);
  a35=(a10*a21);
  a28=(a8*a12);
  a35=(a35+a28);
  a28=(a18*a45);
  a35=(a35+a28);
  a28=casadi_sq(a35);
  a4=(a4+a28);
  a28=(a10*a27);
  a48=(a8*a32);
  a28=(a28+a48);
  a48=(a18*a46);
  a28=(a28+a48);
  a48=casadi_sq(a28);
  a4=(a4+a48);
  a10=(a10*a34);
  a8=(a8*a11);
  a10=(a10+a8);
  a18=(a18*a47);
  a10=(a10+a18);
  a18=casadi_sq(a10);
  a4=(a4+a18);
  a18=(a20*a4);
  a8=(a16*a9);
  a48=(a25*a1);
  a8=(a8+a48);
  a48=(a31*a17);
  a8=(a8+a48);
  a48=(a38*a42);
  a8=(a8+a48);
  a48=(a43*a39);
  a8=(a8+a48);
  a48=(a13*a35);
  a8=(a8+a48);
  a48=(a22*a28);
  a8=(a8+a48);
  a48=(a2*a10);
  a8=(a8+a48);
  a48=(a9*a16);
  a49=(a1*a25);
  a48=(a48+a49);
  a49=(a17*a31);
  a48=(a48+a49);
  a49=(a42*a38);
  a48=(a48+a49);
  a49=(a39*a43);
  a48=(a48+a49);
  a49=(a35*a13);
  a48=(a48+a49);
  a49=(a28*a22);
  a48=(a48+a49);
  a49=(a10*a2);
  a48=(a48+a49);
  a49=(a8*a48);
  a18=(a18-a49);
  a49=cos(a3);
  a6=(a49*a6);
  a6=(a0*a6);
  a14=(a6*a14);
  a49=(a49*a7);
  a49=(a0*a49);
  a15=(a49*a15);
  a14=(a14-a15);
  a3=sin(a3);
  a0=(a0*a3);
  a19=(a0*a19);
  a14=(a14+a19);
  a19=casadi_sq(a14);
  a23=(a6*a23);
  a24=(a49*a24);
  a23=(a23-a24);
  a26=(a0*a26);
  a23=(a23+a26);
  a26=casadi_sq(a23);
  a19=(a19+a26);
  a29=(a6*a29);
  a30=(a49*a30);
  a29=(a29-a30);
  a33=(a0*a33);
  a29=(a29+a33);
  a33=casadi_sq(a29);
  a19=(a19+a33);
  a36=(a6*a36);
  a37=(a49*a37);
  a36=(a36-a37);
  a40=(a0*a40);
  a36=(a36+a40);
  a40=casadi_sq(a36);
  a19=(a19+a40);
  a5=(a6*a5);
  a44=(a49*a44);
  a5=(a5-a44);
  a41=(a0*a41);
  a5=(a5-a41);
  a41=casadi_sq(a5);
  a19=(a19+a41);
  a12=(a6*a12);
  a21=(a49*a21);
  a12=(a12-a21);
  a45=(a0*a45);
  a12=(a12-a45);
  a45=casadi_sq(a12);
  a19=(a19+a45);
  a32=(a6*a32);
  a27=(a49*a27);
  a32=(a32-a27);
  a46=(a0*a46);
  a32=(a32-a46);
  a46=casadi_sq(a32);
  a19=(a19+a46);
  a6=(a6*a11);
  a49=(a49*a34);
  a6=(a6-a49);
  a0=(a0*a47);
  a6=(a6-a0);
  a0=casadi_sq(a6);
  a19=(a19+a0);
  a0=(a20*a4);
  a47=(a8*a48);
  a0=(a0-a47);
  a0=(a19*a0);
  a47=(a5*a43);
  a49=(a14*a16);
  a34=(a23*a25);
  a49=(a49+a34);
  a34=(a29*a31);
  a49=(a49+a34);
  a34=(a36*a38);
  a49=(a49+a34);
  a47=(a47-a49);
  a49=(a12*a13);
  a47=(a47+a49);
  a49=(a32*a22);
  a47=(a47+a49);
  a49=(a6*a2);
  a47=(a47+a49);
  a43=(a43*a5);
  a16=(a16*a14);
  a25=(a25*a23);
  a16=(a16+a25);
  a31=(a31*a29);
  a16=(a16+a31);
  a38=(a38*a36);
  a16=(a16+a38);
  a43=(a43-a16);
  a13=(a13*a12);
  a43=(a43+a13);
  a22=(a22*a32);
  a43=(a43+a22);
  a2=(a2*a6);
  a43=(a43+a2);
  a2=(a43*a4);
  a22=(a9*a14);
  a13=(a1*a23);
  a22=(a22+a13);
  a13=(a17*a29);
  a22=(a22+a13);
  a13=(a42*a36);
  a22=(a22+a13);
  a13=(a39*a5);
  a22=(a22-a13);
  a13=(a35*a12);
  a22=(a22-a13);
  a13=(a28*a32);
  a22=(a22-a13);
  a13=(a10*a6);
  a22=(a22-a13);
  a13=(a8*a22);
  a2=(a2+a13);
  a2=(a47*a2);
  a0=(a0-a2);
  a14=(a14*a9);
  a23=(a23*a1);
  a14=(a14+a23);
  a29=(a29*a17);
  a14=(a14+a29);
  a36=(a36*a42);
  a14=(a14+a36);
  a5=(a5*a39);
  a14=(a14-a5);
  a12=(a12*a35);
  a14=(a14-a12);
  a32=(a32*a28);
  a14=(a14-a32);
  a6=(a6*a10);
  a14=(a14-a6);
  a6=(a43*a48);
  a10=(a20*a22);
  a6=(a6+a10);
  a6=(a14*a6);
  a0=(a0-a6);
  a18=(a18/a0);
  if (res[0]!=0) res[0][0]=a18;
  a18=(a43*a4);
  a6=(a8*a22);
  a18=(a18+a6);
  a18=(a18/a0);
  a18=(-a18);
  if (res[0]!=0) res[0][1]=a18;
  a18=(a43*a48);
  a6=(a20*a22);
  a18=(a18+a6);
  a18=(a18/a0);
  a18=(-a18);
  if (res[0]!=0) res[0][2]=a18;
  a18=(a47*a4);
  a6=(a14*a48);
  a18=(a18+a6);
  a18=(a18/a0);
  a18=(-a18);
  if (res[0]!=0) res[0][3]=a18;
  a4=(a19*a4);
  a18=(a14*a22);
  a4=(a4-a18);
  a4=(a4/a0);
  if (res[0]!=0) res[0][4]=a4;
  a48=(a19*a48);
  a22=(a47*a22);
  a48=(a48+a22);
  a48=(a48/a0);
  if (res[0]!=0) res[0][5]=a48;
  a48=(a47*a8);
  a22=(a14*a20);
  a48=(a48+a22);
  a48=(a48/a0);
  a48=(-a48);
  if (res[0]!=0) res[0][6]=a48;
  a8=(a19*a8);
  a14=(a14*a43);
  a8=(a8+a14);
  a8=(a8/a0);
  if (res[0]!=0) res[0][7]=a8;
  a19=(a19*a20);
  a47=(a47*a43);
  a19=(a19-a47);
  a19=(a19/a0);
  if (res[0]!=0) res[0][8]=a19;
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int jerk_ellips(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT int jerk_ellips_alloc_mem(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int jerk_ellips_init_mem(int mem) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void jerk_ellips_free_mem(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT int jerk_ellips_checkout(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void jerk_ellips_release(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT void jerk_ellips_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void jerk_ellips_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int jerk_ellips_n_in(void) { return 3;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int jerk_ellips_n_out(void) { return 1;}

extern "C" CASADI_SYMBOL_EXPORT casadi_real jerk_ellips_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* jerk_ellips_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* jerk_ellips_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* jerk_ellips_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* jerk_ellips_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT int jerk_ellips_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_jerk_ellips(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[70];
  casadi_int *iw = 0;
  const casadi_real* arg[3] = {0};
  casadi_real* res[1] = {0};
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"jerk_ellips\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"jerk_ellips\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+20);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+3, casadi_s1, w+20);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+7, casadi_s1, w+20);
  --resc;
  res[0] = w+11;
  i = jerk_ellips(arg, res, iw, w+20, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"jerk_ellips\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s3, res[0]);
}
#endif

casadi_int main_jerk_ellips(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[70];
  const casadi_real* arg[3];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+3;
  arg[2] = w+7;
  res[0] = w+11;
  a = w;
  for (j=0; j<11; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = jerk_ellips(arg, res, iw, w+20, 0);
  if (flag) return flag;
  r = w+11;
  for (j=0; j<9; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
extern "C"
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[12];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    /* name error */
  } else if (strcmp(buf, "A_jerk_fun")==0) {
    mex_A_jerk_fun(resc, resv, argc-1, argv+1);
    return;
  } else if (strcmp(buf, "jerk_ellips")==0) {
    mex_jerk_ellips(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'A_jerk_fun' 'jerk_ellips'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "A_jerk_fun")==0) {
    return main_A_jerk_fun(argc-2, argv+2);
  } else if (strcmp(argv[1], "jerk_ellips")==0) {
    return main_jerk_ellips(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'A_jerk_fun' 'jerk_ellips'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
