/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int A_jerk_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int A_jerk_fun_alloc_mem(void);
extern "C" int A_jerk_fun_init_mem(int mem);
extern "C" void A_jerk_fun_free_mem(int mem);
extern "C" int A_jerk_fun_checkout(void);
extern "C" void A_jerk_fun_release(int mem);
extern "C" void A_jerk_fun_incref(void);
extern "C" void A_jerk_fun_decref(void);
extern "C" casadi_int A_jerk_fun_n_out(void);
extern "C" casadi_int A_jerk_fun_n_in(void);
extern "C" casadi_real A_jerk_fun_default_in(casadi_int i);
extern "C" const char* A_jerk_fun_name_in(casadi_int i);
extern "C" const char* A_jerk_fun_name_out(casadi_int i);
extern "C" const casadi_int* A_jerk_fun_sparsity_in(casadi_int i);
extern "C" const casadi_int* A_jerk_fun_sparsity_out(casadi_int i);
extern "C" int A_jerk_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int jerk_ellips(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int jerk_ellips_alloc_mem(void);
extern "C" int jerk_ellips_init_mem(int mem);
extern "C" void jerk_ellips_free_mem(int mem);
extern "C" int jerk_ellips_checkout(void);
extern "C" void jerk_ellips_release(int mem);
extern "C" void jerk_ellips_incref(void);
extern "C" void jerk_ellips_decref(void);
extern "C" casadi_int jerk_ellips_n_out(void);
extern "C" casadi_int jerk_ellips_n_in(void);
extern "C" casadi_real jerk_ellips_default_in(casadi_int i);
extern "C" const char* jerk_ellips_name_in(casadi_int i);
extern "C" const char* jerk_ellips_name_out(casadi_int i);
extern "C" const casadi_int* jerk_ellips_sparsity_in(casadi_int i);
extern "C" const casadi_int* jerk_ellips_sparsity_out(casadi_int i);
extern "C" int jerk_ellips_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
